name: Postman to K6 Conversion with Load Testing Configuration

on:
  push:
    branches:
      - main

jobs:
  postman-to-k6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Postman-to-K6 Converter
        run: npm install -g postman-to-k6

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install -y k6

      - name: Convert Postman Collection to K6 Script
        run: |
          postman-to-k6 ./.postman/collection/Memcrypt_qa_performance.postman_collection.json \
            -e ./.postman/env/memcrypt_qa.postman_environment.json \
            -o ./grafana/scripts/k6script.js

      - name: Print current directory
        run: |
          echo "Current directory of k6:"
          pwd
          echo "Listing files in ./grafana/scripts:"
          ls -l ./grafana/scripts

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y docker docker-engine docker.io containerd runc
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Print current directory
        run: |
          echo "Current directory of docker compose:"
          pwd

      - name: Run K6 Load Test
        run: |
          docker-compose -f ./grafana/docker-compose.yml up -d
          docker-compose -f ./grafana/docker-compose.yml logs -f

      - name: Shutdown Docker Compose
        run: |
          docker-compose -f ./grafana/docker-compose.yml down -v
