name: Postman to K6 Conversion and Load Testing

on:
  push:
    branches:
      - main

jobs:
  # Job to convert Postman collection to K6 script
  convert-to-k6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Postman-to-K6 Converter
        run: npm install -g postman-to-k6

      - name: Convert Postman Collection to K6 Script
        run: |
          postman-to-k6 ./.postman/collection/Memcrypt_qa_performance.postman_collection.json \
            -e ./.postman/env/memcrypt_qa.postman_environment.json \
            -o ./grafana/scripts/k6script.js

      - name: Check if k6 script exists
        run: |
          ls -l ./grafana/scripts/k6script.js

      - name: Upload the k6 script as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: k6script
          path: ./grafana/scripts/k6script.js

  # Job to run the K6 load test
  run-load-test:
    runs-on: ubuntu-latest
    needs: convert-to-k6  # This job depends on the completion of the conversion job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Download the k6 script artifact
        uses: actions/download-artifact@v3
        with:
          name: k6script
          path: ./grafana/scripts

      - name: List contents of /scripts to verify file mounting
        run: ls -l ./grafana/scripts

      - name: Run K6 Load Test
        run: |
          docker-compose -f ./grafana/docker-compose.yml up -d
          docker-compose -f ./grafana/docker-compose.yml logs -f

      - name: Shutdown Docker Compose
        run: |
          docker-compose -f ./grafana/docker-compose.yml down -v
